<?php

namespace FM\ApiBundle\Repository;

use FM\ApiBundle\Entity\ProviderProfile;

/**
 * RateServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateServiceRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get all rate type ID & name
     * 
     * @return type
     */
    public function getAllRateService()
    {

        return $this->createQueryBuilder('rs')
                        ->leftJoin('rs.category', 'rc')
                        ->orderBy('rs.itemName', 'ASC')
                        ->getQuery()
                        ->getResult();
    }
    
    /**
     * Get rate type ID & name by id
     * 
     * @return type
     */
    public function getRateServiceByCategory($categoryId, $provider)
    {
        $result = $this->createQueryBuilder('rs')
                        ->leftJoin('rs.category', 'rc')
                        ->where('rs.category = :categoryId')
                        ->setParameter('categoryId', $categoryId)
                        ->orderBy('rs.id', 'ASC')
                        ->getQuery()
                        ->getResult();
        return $result;
    }
    
}
